apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-api-logs-pvc # Nombre usado en el Deployment
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: standard
