# pvc-public-api.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-public-api
  namespace: public
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
