---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-api-logs-pvc
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: private-api-config
  namespace: public
data:
  DB_HOST: mysql
  DB_PORT: "3306"
  DB_USER: root
  DB_PASSWORD: example
  DB_NAME: private_db

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: public-api-hpa
  namespace: public
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: public-api-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70
