apiVersion: batch/v1
kind: Job
metadata:
  name: hello-job
  namespace: private
spec:
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ["echo", "Hola, desde Kubernetes!"]
      restartPolicy: Never
  backoffLimit: 4
