apiVersion: v1
kind: PersistentVolume
metadata:
  name: public-api-logs-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard  # ✅ este campo es clave
  hostPath:
    path: /mnt/data/public-api-logs
