apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: public
  labels:
    app: nginx-public
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: private
  labels:
    app: nginx-private
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
