apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-api-logs-pvc
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: standard
