apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: public
data:
  config.js: |
    var config = (() => {
      return {
        API: "http://api.fercanap.kubelabs.dev/graphql",
        WEBSOCKET: "ws://websocket.fercanap.kubelabs.dev/graphql",
      };
    })();
