apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-public-api
  namespace: public
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: public-api
  minReplicas: 3
  maxReplicas: 6
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 35
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50
