apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: public-api-pvc
  namespace: public
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 50Mi
